/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by: node deploy/worker/generate-routes.js
 *
 * Phase-1 scope: /api/auth/* only.
 */

import * as mwApi from '../functions/api/_middleware.js';
import * as apiAuthAdminLogin from '../functions/api/auth/adminLogin.js';
import * as apiAuthLogin from '../functions/api/auth/login.js';
import * as apiAuthLogout from '../functions/api/auth/logout.js';
import * as apiAuthResetAuth from '../functions/api/auth/resetAuth.js';
import * as apiAuthSessionCheck from '../functions/api/auth/sessionCheck.js';

const GENERATED_AUTH_ROUTES = new Map([
    ['/api/auth/adminLogin', { module: apiAuthAdminLogin, middlewares: [mwApi] }],
    ['/api/auth/login', { module: apiAuthLogin, middlewares: [mwApi] }],
    ['/api/auth/logout', { module: apiAuthLogout, middlewares: [mwApi] }],
    ['/api/auth/resetAuth', { module: apiAuthResetAuth, middlewares: [mwApi] }],
    ['/api/auth/sessionCheck', { module: apiAuthSessionCheck, middlewares: [mwApi] }],
]);

export function matchGeneratedAuthRoute(pathname) {
    const normalizedPath = pathname.length > 1 && pathname.endsWith('/')
        ? pathname.slice(0, -1)
        : pathname;

    return GENERATED_AUTH_ROUTES.get(normalizedPath) || null;
}
