/**
 * Generate subordinate worker routes for phase-1 safe paths only.
 *
 * This is intentionally narrower than upstream route generation:
 * - current allowlist: functions/api/auth/*.js
 * - current output: src/generatedAuthRoutes.js
 * - current purpose: let src/worker.js remain the main entry while
 *   delegating only /api/auth/* endpoints to a generated manifest.
 */

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'fs';
import { basename, dirname, join, relative } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '../..');
const FUNCTIONS_DIR = join(ROOT, 'functions');
const AUTH_DIR = join(FUNCTIONS_DIR, 'api', 'auth');
const OUTPUT_FILE = join(ROOT, 'src', 'generatedAuthRoutes.js');

function hasRouteExport(filePath) {
    const content = readFileSync(filePath, 'utf8');
    return /export\s+(async\s+)?function\s+onRequest(?:[A-Z][A-Za-z]+)?\b/m.test(content)
        || /export\s+const\s+onRequest(?:[A-Z][A-Za-z]+)?\b/m.test(content);
}

function toImportVar(relPath) {
    return relPath
        .replace(/\\/g, '/')
        .replace(/\.js$/, '')
        .split(/[\/\-.]/)
        .map((part, index) => index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1))
        .join('');
}

function toRoutePath(relPath) {
    const normalized = relPath.replace(/\\/g, '/').replace(/\.js$/, '');
    return `/${normalized}`;
}

const files = readdirSync(AUTH_DIR)
    .filter((entry) => entry.endsWith('.js'))
    .sort()
    .map((entry) => join(AUTH_DIR, entry))
    .filter((filePath) => hasRouteExport(filePath));

const imports = ["import * as mwApi from '../functions/api/_middleware.js';"];
const entries = [];

for (const filePath of files) {
    const relPath = relative(FUNCTIONS_DIR, filePath).replace(/\\/g, '/');
    const importVar = toImportVar(relPath);
    const routePath = toRoutePath(relPath);
    imports.push(`import * as ${importVar} from '../functions/${relPath}';`);
    entries.push(`    ['${routePath}', { module: ${importVar}, middlewares: [mwApi] }],`);
}

const output = `/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by: node deploy/worker/generate-routes.js
 *
 * Phase-1 scope: /api/auth/* only.
 */

${imports.join('\n')}

const GENERATED_AUTH_ROUTES = new Map([
${entries.join('\n')}
]);

export function matchGeneratedAuthRoute(pathname) {
    const normalizedPath = pathname.length > 1 && pathname.endsWith('/')
        ? pathname.slice(0, -1)
        : pathname;

    return GENERATED_AUTH_ROUTES.get(normalizedPath) || null;
}
`;

mkdirSync(dirname(OUTPUT_FILE), { recursive: true });
writeFileSync(OUTPUT_FILE, output, 'utf8');

console.log(`✓ Generated ${basename(OUTPUT_FILE)} with ${entries.length} auth route(s)`);
