/**
 * 路由生成与校验
 *
 * 两件事：
 *   1. 生成：把 functions/api/auth/*.js 渲染成 src/generatedAuthRoutes.js
 *      （这些端点的路由路径可由文件路径直接推导，适合生成）
 *   2. 校验：全量检查 functions/ 下的 handler 是否都被登记（见 route-coverage.js）
 *
 * 为什么只对 api/auth 做生成、而对其余做校验：
 * 本项目存在无法由文件路径推导的路由 —— /music、/music/、/music.html 三条路径
 * 指向同一 handler；/api/site/storage-overview 是 /api/manage/stats 的别名；
 * 部分动态路由需要函数式参数提取。全量生成需要引入一套描述这些情况的 DSL，
 * 复杂度高于收益。而「全量校验」能以极低成本消除漏登记导致的静默失败。
 *
 * 输出：src/generatedAuthRoutes.js
 * 用法：
 *   node deploy/worker/generate-routes.js           # 生成
 *   node deploy/worker/generate-routes.js --check   # 只校验，不修改（CI 用）
 */

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'fs';
import { basename, dirname, join, relative, resolve } from 'path';
import { fileURLToPath } from 'url';
import { verifyRouteCoverage, formatCoverageResult } from './route-coverage.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
export const ROOT = join(__dirname, '../..');
export const FUNCTIONS_DIR = join(ROOT, 'functions');
export const AUTH_DIR = join(FUNCTIONS_DIR, 'api', 'auth');
export const OUTPUT_FILE = join(ROOT, 'src', 'generatedAuthRoutes.js');
export const ROUTES_FILE = join(ROOT, 'src', 'routes.js');

export function hasRouteExport(filePath) {
    const content = readFileSync(filePath, 'utf8');
    return /export\s+(async\s+)?function\s+onRequest(?:[A-Z][A-Za-z]+)?\b/m.test(content)
        || /export\s+const\s+onRequest(?:[A-Z][A-Za-z]+)?\b/m.test(content);
}

export function toImportVar(relPath) {
    return relPath
        .replace(/\\/g, '/')
        .replace(/\.js$/, '')
        .split(/[\/\-.]/)
        .map((part, index) => index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1))
        .join('');
}

export function toRoutePath(relPath) {
    const normalized = relPath.replace(/\\/g, '/').replace(/\.js$/, '');
    return `/${normalized}`;
}

export function collectAuthRouteFiles(authDir = AUTH_DIR) {
    return readdirSync(authDir)
        .filter((entry) => entry.endsWith('.js'))
        .sort()
        .map((entry) => join(authDir, entry))
        .filter((filePath) => hasRouteExport(filePath));
}

export function renderGeneratedAuthRoutes({
    authDir = AUTH_DIR,
    functionsDir = FUNCTIONS_DIR,
} = {}) {
    const imports = ["import * as mwApi from '../functions/api/_middleware.js';"];
    const entries = [];

    for (const filePath of collectAuthRouteFiles(authDir)) {
        const relPath = relative(functionsDir, filePath).replace(/\\/g, '/');
        const importVar = toImportVar(relPath);
        const routePath = toRoutePath(relPath);
        imports.push(`import * as ${importVar} from '../functions/${relPath}';`);
        entries.push(`    ['${routePath}', { module: ${importVar}, middlewares: [mwApi] }],`);
    }

    return `/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by: node deploy/worker/generate-routes.js
 *
 * Phase-1 scope: /api/auth/* only.
 */

${imports.join('\n')}

const GENERATED_AUTH_ROUTES = new Map([
${entries.join('\n')}
]);

export function matchGeneratedAuthRoute(pathname) {
    const normalizedPath = pathname.length > 1 && pathname.endsWith('/')
        ? pathname.slice(0, -1)
        : pathname;

    return GENERATED_AUTH_ROUTES.get(normalizedPath) || null;
}
`;
}

/**
 * 统一行尾后再比较。
 *
 * 背景：生成器产出 LF，但 Windows 工作区在 core.autocrlf=true 时 checkout 为
 * CRLF，直接字符串比较会把「行尾差异」误判成「生成物过期」，导致
 * npm test 在 Windows 上必然失败、在 Linux 上通过。此处做规范化比较，
 * 同时用 .gitattributes 从源头约束行尾。
 */
function normalizeEol(text) {
    return text.replace(/\r\n/g, '\n');
}

export function isGeneratedRouteFileCurrent(outputFile = OUTPUT_FILE, expectedOutput = renderGeneratedAuthRoutes()) {
    try {
        return normalizeEol(readFileSync(outputFile, 'utf8')) === normalizeEol(expectedOutput);
    } catch (error) {
        if (error?.code === 'ENOENT') {
            return false;
        }
        throw error;
    }
}

/**
 * 校验全量路由覆盖：functions/ 下每个导出 onRequest 的 handler
 * 都应被 src/routes.js 或 src/generatedAuthRoutes.js 覆盖。
 *
 * 这是「漏登记静默失败」的防线 —— 详见 route-coverage.js 的模块注释。
 */
export function verifyRoutes() {
    const coverage = verifyRouteCoverage({
        functionsDir: FUNCTIONS_DIR,
        routesFile: ROUTES_FILE,
        generatedFile: OUTPUT_FILE,
    });
    console.log(formatCoverageResult(coverage));
    return coverage.ok;
}

export function generateAuthRoutes({ check = false } = {}) {
    const output = renderGeneratedAuthRoutes();

    if (check) {
        let ok = true;

        if (!isGeneratedRouteFileCurrent(OUTPUT_FILE, output)) {
            console.error(`✗ ${basename(OUTPUT_FILE)} is stale; run npm run generate:worker-routes`);
            ok = false;
        } else {
            console.log(`✓ Verified ${basename(OUTPUT_FILE)} is current`);
        }

        // 除生成物新鲜度外，同时校验全量路由覆盖（覆盖范围远大于 api/auth）
        if (!verifyRoutes()) {
            ok = false;
        }

        return ok;
    }

    mkdirSync(dirname(OUTPUT_FILE), { recursive: true });
    writeFileSync(OUTPUT_FILE, output, 'utf8');
    console.log(`✓ Generated ${basename(OUTPUT_FILE)} with ${collectAuthRouteFiles().length} auth route(s)`);
    return true;
}

const isMainModule = process.argv[1]
    && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isMainModule) {
    const supportedArgs = new Set(['--check']);
    const unknownArg = process.argv.slice(2).find((arg) => !supportedArgs.has(arg));
    if (unknownArg) {
        console.error(`Unknown argument: ${unknownArg}`);
        process.exitCode = 2;
    } else if (!generateAuthRoutes({ check: process.argv.includes('--check') })) {
        process.exitCode = 1;
    }
}
