/**
 * Generate subordinate worker routes for phase-1 safe paths only.
 *
 * This is intentionally narrower than upstream route generation:
 * - current allowlist: functions/api/auth/*.js
 * - current output: src/generatedAuthRoutes.js
 * - current purpose: let src/worker.js remain the main entry while
 *   delegating only /api/auth/* endpoints to a generated manifest.
 */

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'fs';
import { basename, dirname, join, relative, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
export const ROOT = join(__dirname, '../..');
export const FUNCTIONS_DIR = join(ROOT, 'functions');
export const AUTH_DIR = join(FUNCTIONS_DIR, 'api', 'auth');
export const OUTPUT_FILE = join(ROOT, 'src', 'generatedAuthRoutes.js');

export function hasRouteExport(filePath) {
    const content = readFileSync(filePath, 'utf8');
    return /export\s+(async\s+)?function\s+onRequest(?:[A-Z][A-Za-z]+)?\b/m.test(content)
        || /export\s+const\s+onRequest(?:[A-Z][A-Za-z]+)?\b/m.test(content);
}

export function toImportVar(relPath) {
    return relPath
        .replace(/\\/g, '/')
        .replace(/\.js$/, '')
        .split(/[\/\-.]/)
        .map((part, index) => index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1))
        .join('');
}

export function toRoutePath(relPath) {
    const normalized = relPath.replace(/\\/g, '/').replace(/\.js$/, '');
    return `/${normalized}`;
}

export function collectAuthRouteFiles(authDir = AUTH_DIR) {
    return readdirSync(authDir)
        .filter((entry) => entry.endsWith('.js'))
        .sort()
        .map((entry) => join(authDir, entry))
        .filter((filePath) => hasRouteExport(filePath));
}

export function renderGeneratedAuthRoutes({
    authDir = AUTH_DIR,
    functionsDir = FUNCTIONS_DIR,
} = {}) {
    const imports = ["import * as mwApi from '../functions/api/_middleware.js';"];
    const entries = [];

    for (const filePath of collectAuthRouteFiles(authDir)) {
        const relPath = relative(functionsDir, filePath).replace(/\\/g, '/');
        const importVar = toImportVar(relPath);
        const routePath = toRoutePath(relPath);
        imports.push(`import * as ${importVar} from '../functions/${relPath}';`);
        entries.push(`    ['${routePath}', { module: ${importVar}, middlewares: [mwApi] }],`);
    }

    return `/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by: node deploy/worker/generate-routes.js
 *
 * Phase-1 scope: /api/auth/* only.
 */

${imports.join('\n')}

const GENERATED_AUTH_ROUTES = new Map([
${entries.join('\n')}
]);

export function matchGeneratedAuthRoute(pathname) {
    const normalizedPath = pathname.length > 1 && pathname.endsWith('/')
        ? pathname.slice(0, -1)
        : pathname;

    return GENERATED_AUTH_ROUTES.get(normalizedPath) || null;
}
`;
}

export function isGeneratedRouteFileCurrent(outputFile = OUTPUT_FILE, expectedOutput = renderGeneratedAuthRoutes()) {
    try {
        return readFileSync(outputFile, 'utf8') === expectedOutput;
    } catch (error) {
        if (error?.code === 'ENOENT') {
            return false;
        }
        throw error;
    }
}

export function generateAuthRoutes({ check = false } = {}) {
    const output = renderGeneratedAuthRoutes();

    if (check) {
        if (!isGeneratedRouteFileCurrent(OUTPUT_FILE, output)) {
            console.error(`✗ ${basename(OUTPUT_FILE)} is stale; run npm run generate:worker-routes`);
            return false;
        }

        console.log(`✓ Verified ${basename(OUTPUT_FILE)} is current`);
        return true;
    }

    mkdirSync(dirname(OUTPUT_FILE), { recursive: true });
    writeFileSync(OUTPUT_FILE, output, 'utf8');
    console.log(`✓ Generated ${basename(OUTPUT_FILE)} with ${collectAuthRouteFiles().length} auth route(s)`);
    return true;
}

const isMainModule = process.argv[1]
    && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isMainModule) {
    const supportedArgs = new Set(['--check']);
    const unknownArg = process.argv.slice(2).find((arg) => !supportedArgs.has(arg));
    if (unknownArg) {
        console.error(`Unknown argument: ${unknownArg}`);
        process.exitCode = 2;
    } else if (!generateAuthRoutes({ check: process.argv.includes('--check') })) {
        process.exitCode = 1;
    }
}
